name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '*.md'
      - 'docs/**/*.md'
      - 'Cargo.toml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '*.md'
      - 'docs/**/*.md'
      - 'Cargo.toml'

jobs:
  docs:
    name: Documentation Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-docs-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Build documentation
        run: cargo doc --no-deps --document-private-items --all-features
        env:
          RUSTDOCFLAGS: -D warnings
          
      - name: Install markdownlint
        run: npm install -g markdownlint-cli2
        
      - name: Auto-fix markdown formatting
        run: markdownlint-cli2 --fix "**/*.md" "!target/**" "!node_modules/**"
        
      - name: Lint markdown files
        run: markdownlint-cli2 "**/*.md" "!target/**" "!node_modules/**"
