name: Maintenance

on:
  schedule:
    # Run weekly on Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  # Check for outdated dependencies
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install cargo-outdated
        run: cargo install cargo-outdated --locked
        
      - name: Check outdated dependencies
        run: cargo outdated --verbose
        
      - name: Install cargo-tree
        run: cargo install cargo-tree --locked
        
      - name: Show dependency tree
        run: cargo tree

  # Update Cargo.lock and test
  update-lockfile:
    name: Update Lockfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Update Cargo.lock
        run: cargo update
        
      - name: Test with updated dependencies
        run: cargo test --verbose
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update Cargo.lock dependencies'
          title: 'chore: update Cargo.lock dependencies'
          body: |
            Automated dependency update via GitHub Actions.
            
            This PR updates the `Cargo.lock` file with the latest compatible versions
            of all dependencies while maintaining semver compatibility.
            
            All tests have been run and pass with the updated dependencies.
          branch: chore/update-dependencies
          delete-branch: true

  # Check for security advisories
  security-advisory:
    name: Security Advisory Check  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install cargo-audit
        run: cargo install cargo-audit --locked
        
      - name: Run security audit
        run: cargo audit --json > audit-report.json
        
      - name: Upload audit report
        uses: actions/upload-artifact@v3
        with:
          name: security-audit-report
          path: audit-report.json
